.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeAssignment-Letter_Pyramid - Debug ]----------"
	@cd "ChallengeAssignment-Letter_Pyramid" && "$(MAKE)" -f  "ChallengeAssignment-Letter_Pyramid.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeAssignment-Letter_Pyramid - Debug ]----------"
	@cd "ChallengeAssignment-Letter_Pyramid" && "$(MAKE)" -f  "ChallengeAssignment-Letter_Pyramid.mk" clean
