.PHONY: clean All

All:
	@echo "----------Building project:[ PassingPointers1 - Debug ]----------"
	@cd "PassingPointers1" && "$(MAKE)" -f  "PassingPointers1.mk"
clean:
	@echo "----------Cleaning project:[ PassingPointers1 - Debug ]----------"
	@cd "PassingPointers1" && "$(MAKE)" -f  "PassingPointers1.mk" clean
