.PHONY: clean All

All:
	@echo "----------Building project:[ ChallangeSolution - Debug ]----------"
	@cd "ChallangeSolution" && "$(MAKE)" -f  "ChallangeSolution.mk"
clean:
	@echo "----------Cleaning project:[ ChallangeSolution - Debug ]----------"
	@cd "ChallangeSolution" && "$(MAKE)" -f  "ChallangeSolution.mk" clean
